name: statsy
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.27.0
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  uuid: ^4.3.3
  get_it: ^7.6.7
  provider: ^6.1.2
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10+1
  flutter_dotenv: ^5.1.0
  google_generative_ai: ^0.2.2
  flutter_markdown: ^0.6.22
  flare_flutter: ^3.0.2
  firebase_storage: ^11.6.11

  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/icon-android.png"
  android: true
  ios: true

flutter_icons:
  image_path: "assets/images/icon.png"
  android: "launcher_icon"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon-android.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/google_icon.svg
    - assets/images/logo.svg
    - assets/images/logo-gray.svg
    - .env

  fonts:
    - family: OrelegaOne
      fonts:
        - asset: assets/fonts/OrelegaOne-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
